# Generated by Django 3.1.2 on 2020-11-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acbookingstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coachstructureac',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coachstructuresleeper',
            options={},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sleeperbookingstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trainschedule',
            options={},
        ),
    ]
