# Generated by Django 3.1.2 on 2020-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201123_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainschedule',
            name='journey_date',
            field=models.DateField(),
        ),
    ]
