# Generated by Django 3.1.2 on 2020-11-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201123_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.trainschedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(default='AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='acbookingstatus',
            name='coachNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleeperbookingstatus',
            name='coachNumber',
            field=models.IntegerField(),
        ),
    ]
