# Generated by Django 3.1.2 on 2020-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
