# Generated by Django 3.1.2 on 2020-11-19 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookingagent_credit_card'),
        ('bookings', '0004_auto_20201119_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachStructureAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField()),
                ('seatType', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CoachStructureSleeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField()),
                ('seatType', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('pnrNumber', models.CharField(max_length=12)),
                ('booking_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.bookingagent')),
                ('passenger1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket1', to='bookings.passenger')),
                ('passenger2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket2', to='bookings.passenger')),
                ('passenger3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket3', to='bookings.passenger')),
                ('passenger4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket4', to='bookings.passenger')),
                ('passenger5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket5', to='bookings.passenger')),
                ('passenger6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket6', to='bookings.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='SleeperBookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachNumber', models.CharField(max_length=5)),
                ('seatNumber', models.IntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.trainschedule')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfACSeatsRemaining', models.IntegerField()),
                ('noOfSleeperSeatsRemaining', models.IntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.trainschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ACBookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachNumber', models.CharField(max_length=5)),
                ('seatNumber', models.IntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.trainschedule')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ticket')),
            ],
        ),
    ]
