# Generated by Django 3.1.2 on 2020-11-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20201120_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket1', to='bookings.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket2', to='bookings.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket3', to='bookings.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket4', to='bookings.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket5', to='bookings.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket6', to='bookings.passenger'),
        ),
    ]
