# Generated by Django 3.1.2 on 2020-11-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('j_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('no_of_stops', models.IntegerField()),
                ('train_name', models.CharField(max_length=30)),
                ('train_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('stop_number', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_search.journey')),
            ],
        ),
    ]
