# Generated by Django 3.1.2 on 2020-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_search', '0002_routes'),
    ]

    operations = [
    ]
